.PHONY: all clean

CC=gcc
CFLAGS=-Wall -O3 -lm

all: pythagoreanTriplets


pythagoreanTriplets: pythagoreanTriplets.c
	$(CC) $(CFLAGS) -o pythagoreanTriplets pythagoreanTriplets.c

clean:
	rm -rf pythagoreanTriplets.o pythagoreanTriplets

